const express = require('express')
const router = express.Router()
const {validateUser, validateSubscriptionStatus} = require('./userValidate')
const { signup, login, logout, current, uploadAvatar} = require('../../controllers/users')
const guard = require('../../helpers/guard')
const loginLimit = require('../../helpers/rate-limit-login')
const upload = require('../../helpers/uploads')

router.post('/signup', validateUser, signup)
router.post('/login', validateUser, loginLimit, login)
router.post('/logout', guard, logout)
router.post('/current', guard, current)
router.patch('/avatar', guard, upload.single('avatar'), uploadAvatar)
// router.post('/subscription', guard, updateSubscription)
module.exports = router
